# Generated by Django 3.2.4 on 2021-07-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_rename_pasword_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.DateField(blank=True, null=True),
        ),
    ]
