# Generated by Django 3.2.4 on 2021-07-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0003_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='standard',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
