# Generated by Django 3.2.4 on 2021-07-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0004_auto_20210702_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='standard',
            field=models.CharField(max_length=50),
        ),
    ]
